version: '3'

services:
  #front-end proxy for load balancer
  proxy-front:
    build: ./proxy-frontend
    image: waziup/proxy-frontend:1.1
    ports:
      - "80:80"
      - "443:443"
    network_mode: host

  #proxy for routing internal components
  proxy:
    build: ./proxy
    image: waziup/proxy:1.1
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    extra_hosts:
      - "api-server:127.0.0.1"
      - "dashboard:127.0.0.1"
      - "keycloak:127.0.0.1"
      - "website:127.0.0.1"
      - "staging:127.0.0.1"
    environment:
      - BASE_URL=staging.api.iot.bongolive.co.tz
    entrypoint: "/etc/nginx/conf.d/docker-entrypoint.sh"

  dashboard-production:
    # Specific images should be built for each environment (local, staging, production).
    image: waziup/dashboard:1.1.1-production
    build:
      context: ./dashboard
      args:
        - SERVER_PORT=3000
        - SERVER_URL=https://dashboard.api.iot.bongolive.co.tz
        - KEYCLOAK_URL=https://keycloak.api.iot.bongolive.co.tz/auth
        - API_SERVER_URL=https://api.api.iot.bongolive.co.tz/api
    ports:
      - "3000:3000"

  dashboard-staging:
    # Specific images should be built for each environment (local, staging, production).
    image: waziup/dashboard:1.1-staging
    build:
      context: ./dashboard
      args:
        - SERVER_PORT=3000
        - SERVER_URL=https://dashboard.staging.api.iot.bongolive.co.tz
        - KEYCLOAK_URL=https://keycloak.staging.api.iot.bongolive.co.tz/auth
        - API_SERVER_URL=https://api.staging.api.iot.bongolive.co.tz/api
    ports:
      - "3000:3000"
